[package]
name = "init"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
libc="0.2"

actix-web = "4.9"
serde = { version = "1.0", features = ["derive"] }
mysql = "25.0"

[profile.release]
strip = true
